name: stir-test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build stir
      run: |
          cargo build

  tests:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v2
    - name: Run Unit Tests
      run: |
          cargo test
    - uses: actions/checkout@v2
    - name: Run Documentation examples
      run: |
          cargo test --doc
